# Generated by Django 4.1.4 on 2022-12-10 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_testvalidation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testvalidation',
            name='file_path',
        ),
    ]
